### ISSUE TITLE
The treesitter help parser has been renamed vimdoc in Neovim 0.9

### ISSUE THREAD

**Issue by doctorfree** [VonHeikemen/nvim-starter#4]
Great Neovim starter configs!

Note that in Neovim 0.9 the treesitter `help` parser has been renamed `vimdoc`. Initializing the `nvim-starter` modules that include the treesitter `help` parser in `ensure_installed` fails when using Neovim 0.9.

**Comment by VonHeikemen** [comment]
Thank you for letting me know. Its fixed now.

**Comment by doctorfree** [comment]
Not sure but I think you may need to test for Neovim version otherwise `vimdoc` parser may break Neovim 0.8 initialization.

There are several such issues in 0.9 which is why, i guess, we are still at version 0.

**Comment by VonHeikemen** [comment]
Should be fine. I tested it in a docker container using Neovim `v0.8` and `v0.9`.
